Vagrant.configure("2") do |config|
    config.vm.box = "rockylinux/9"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
    end

    config.vm.network "public_network", bridge: true
end